#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header response

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html

# Obtenir le nom de l'hôte
hostname=$(hostname)

# Ajouter l'en-tête avec le nom de l'hôte
sed -i "/listen 80 default_server;/a add_header X-Served-By $hostname;" /etc/nginx/sites-available/default

# Redémarrer nginx
service nginx restart
