#!/usr/bin/env bash
# Install nginx and add a custom header


apt-get update
apt-get -y install nginx

custom_header="add_header X-Served-By \$hostname;"

sudo sed -i "/http {/a \ \ \ \ $custom_header" /etc/nginx/ngix.conf

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

NEW_RULE="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://www.youtube.com/@tboy54321;\n\t}\n"

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bakup

sudo sed -i "531 #NEW_RULE" /etc/nginx/sites-available/default

service nginx restart
