#!/usr/bin/env bash
#configure load balancer

sudo apt-get -y update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update

sudo apt-get install -y haproxy=2.8.*
and replacing it with just
sudo apt-get -y update
sudo apt-get -y install haproxy

sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo chmod 666 /etc/haproxy/haproxy.cfg
echo "\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend backend-servers

backend backend-servers
    balance roundrobin
    server 319401-web-01 54.146.86.71:80 check
    server 319401-web-02 34.229.189.89:80 check
" >> /etc/haproxy/haproxy.cfg

sudo sed -i 's/^ENABLED=.*/ENABLED=1/' /etc/default/haproxy

sudo service haproxy restart
