#!/usr/bin/env bash
# Bash script that creates a subprocess

# Define the PIDFILE path
PIDFILE=/var/run/my_process.pid

start() {
    ./manage_my_process &
    echo "$!" > "$PIDFILE"
}

stop() {
    sudo kill -15 "$(cat "$PIDFILE")" && rm -f "$PIDFILE"
}

# Define the LSB functions directly in the script
# Instead of using ". /lib/lsb/init-functions"
log_success_msg() {
    echo "Success: $*"
}

log_failure_msg() {
    echo "Failure: $*"
}

log_warning_msg() {
    echo "Warning: $*"
}

log_action_begin_msg() {
    echo "Starting $*..."
}

log_action_end_msg() {
    echo "done."
}

case "$1" in
    start)
       start
       log_success_msg "manage_my_process started"
       ;;
    stop)
       stop
       log_success_msg "manage_my_process stopped"
       ;;
    restart)
       stop
       start
       log_success_msg "manage_my_process restarted"
       ;;
    *)
       echo "Usage: manage_my_process {start|stop|restart}"
esac

exit 0
